#!/bin/bash
clear
echo -e "Format of flag is Runner<answer>\n"
sleep 1
read -p "Enter the answer: " ans
if [ $ans == hidden ]
then
 echo""
 echo "That is right. Here is the code: UDQ1NVcwUkQK" 
else
 echo ""
 echo "That is wrong. Try again."
fi
