#!/bin/bash
clear
echo -e "The answer format is Runner<answer>, but it's a little more tricky.\n"
sleep 1
read -p "Enter the answer: " ans
if [ $ans == ASCii ]
then
 echo""
 echo "That is right. Here is the code: cGFzc3dvcmQK"
else
 echo ""
 echo "That is wrong. Try again."
fi
