#!/bin/bash
clear
echo -e "The answer is the number of files that are identical to Test.conf.\n"
sleep 1
read -p "Enter the answer: " ans
if [ $ans == 2 ]
then
 echo""
 echo "That is right. Here is the code: QWRtaW4xCg=="
else
 echo ""
 echo "That is wrong. Try again."
fi
